enabled: true
updateIntervalMinutes: 1

categoryId: "1502783436853608508"

channels:
  - key: "members"
    type: "members"
    name: "｜👥・{count} Members"
  # - key: "bots"
  #   type: "bots"
  #   name: "Bots: {count}"
  - key: "clients"
    type: "role"
    roleId: "1295001304522948740"
    name: "｜💎・{count} Clients"
